version: '2'
services:
  flask_web_app:
    container_name: flask_web_app
    build: ./Flask_Web_App
    volumes:
      - ./Flask_Web_App:/home/app
    ports:
      - "5000:5000"
    restart: always

  jupyter:
    container_name: jupyter
    build: ./Jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./Jupyter/work:/home/jovyan/work

  bitbank:
    build: ./BitBank
    ports:
      - "10080:10080"
    volumes:
      - ./BitBank:/home/bitbank
    restart: always
