apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: bitbank
  name: bitbank
  namespace: default
  resourceVersion: "44059"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bitbank
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: bitbank
    spec:
      containers:
      - image: milkchocolate22/bitbank:latest
        imagePullPolicy: Always
        name: bitbank
        volumeMounts:
          - mountPath: /home/bitbank/new
            name: bitbank-volume
        ports:
        - containerPort: 10080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: bitbank-volume
          emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
