apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: jupyter
  name: jupyter
  namespace: default
  resourceVersion: "44093"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jupyter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: jupyter
    spec:
      containers:
      - image: milkchocolate22/jupyter:latest
        imagePullPolicy: Always
        name: jupyter
        volumeMounts:
        - mountPath: /home/jovyan/work
          name: jupyter-volume
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: jupyter-volume
        emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
