apiVersion: v1
kind: Service
metadata:
  name: jupyter-http
  labels:
    run: jupyter
  namespace: default
spec:
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    run: jupyter
  sessionAffinity: None
  type: LoadBalancer