apiVersion: v1
kind: Service
metadata:
  name: jupyter-https
  labels:
    run: jupyter
  namespace: default
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8888
  selector:
    run: jupyter
  sessionAffinity: None
  type: LoadBalancer