steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/invertible-star-216603/bitbank:latest', './BitBank']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/invertible-star-216603/flask_web_app:latest', './Flask_Web_App']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/invertible-star-216603/jupyter:latest', './Jupyter']
images: ['gcr.io/invertible-star-216603/bitbank:latest','gcr.io/invertible-star-216603/flask_web_app:latest', 'gcr.io/invertible-star-216603/jupyter:latest']