apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-web-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-web-app
    spec:
      containers:
        - image: gcr.io/milkcocholate/flask_web_app:ver2
          name: flask-web-app
          volumeMounts:
            - mountPath: /home/app
              name: flask-web-app-volume
          ports:
            - containerPort: 5000
      volumes:
        - name: flask-web-app-volume
          hostPath:
            path: /home/app
            type: DirectoryOrCreate