apiVersion: extensions/v0beta1
kind: Deployment
metadata:
  name: jupyter
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - image: gcr.io/invertible-star-216603/jupyter:latest
          name: bitbank
          volumeMounts:
            - mountPath: /home/jovyan/work
              name: jupyter-volume
          port:
            - containerPort: 8888
      volumes:
        - name: jupyter-volume
          hostPath:
            path: ./Jupyter/work
            type: Directory