apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-web-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-web-app
    spec:
      containers:
        - image: gcr.io/invertible-star-216603/flask-web-app:latest
          name: flask-web-app
          volumeMounts:
            - mountPath: /home/app
              name: flask-web-app-volume
          ports:
            - containerPort: 5000
      volumes:
        - name: flask-web-app-volume
          hostPath:
            path: /home/zuuuubo_tetsu/milkcocholate/Flask_Web_App
            type: Directory